### ISSUE TITLE
kuaishou.php 怎么在本地用呀？

### ISSUE THREAD

**Issue by j5465** [iqiqiya/iqiqiya-API#19]
运行kuaishou.php，
本来只会输出一个   “请重试哦” 
然后我在getLocation 函数的第一行的  `  $ch  = curl_init($url);`
下面加了一个
    `echo $ch;`
本来有一个$url='http://m.gifshow.com/s/bM7HaGyz';的运行结果：
```
Resource id #4HTTP/1.1 404 Not Found
Date: Thu, 19 Mar 2020 10:33:30 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 2765
Connection: keep-alive
Set-Cookie: JSESSIONID=8235E5A79577D27D3BB5A36D035144D6; Path=/; HttpOnly
Content-Language: en-US

请重试哦
```
把url换成浏览器里的长连接 返回：
`Resource id #4请重试哦`

我没用过php开发，但我感觉应该是可以直接解析出来下载url的，所以这个php代码的正确使用方法是什么呢？
还是智能post `https://tools.iakie.com/kuaishou/api.php`
然后提取出来下载链接呢？

**Comment by iqiqiya** [comment]
方法一：把原本需要通过get或post请求的url这个参数，直接写死
方法二：本地搭建服务器，可以使用集成环境如phpstudy之类的
方法三：用python或者其他语言根据逻辑重写就好
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: j5465<mailto:notifications@github.com>
发送时间: 2020年3月19日 18:39
收件人: iqiqiya/iqiqiya-API<mailto:iqiqiya-API@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [iqiqiya/iqiqiya-API] kuaishou.php 怎么在本地用呀？ (#19)


运行kuaishou.php，
本来只会输出一个 “请重试哦”
然后我在getLocation 函数的第一行的 $ch = curl_init($url);
下面加了一个
echo $ch;
本来有一个$url='http://m.gifshow.com/s/bM7HaGyz';的运行结果：<http://m.gifshow.com/s/bM7HaGyz';%E7%9A%84%E8%BF%90%E8%A1%8C%E7%BB%93%E6%9E%9C%EF%BC%9A>

Resource id #4HTTP/1.1 404 Not Found

Date: Thu, 19 Mar 2020 10:33:30 GMT

Content-Type: text/html;charset=UTF-8

Content-Length: 2765

Connection: keep-alive

Set-Cookie: JSESSIONID=8235E5A79577D27D3BB5A36D035144D6; Path=/; HttpOnly

Content-Language: en-US



请重试哦

把url换成浏览器里的长连接 返回：
Resource id #4请重试哦

我没用过php开发，但我感觉应该是可以直接解析出来下载url的，所以这个php代码的正确使用方法是什么呢？
还是智能post https://tools.iakie.com/kuaishou/api.php
然后提取出来下载链接呢？

―
