### ISSUE TITLE
解析的视频地址，如何调用？能否解析地址后直接变成下载

### ISSUE THREAD

**Issue by vkkrcom** [iqiqiya/iqiqiya-API#5]
请问代码该如何写？

**Comment by iqiqiya** [comment]
请问您说的是解析哪一个视频地址呢

**Comment by vkkrcom** [comment]
> 请问您说的是解析哪一个视频地址呢

例如网易云音乐在线解析，调用方式https://api.77sec.cn/163music/api.php（中间如何调用？）http://m10.music.126.net/20191020165005/2bac58aec822f96bf6e55dfebad82792/ymusic/8ae5/e063/1d74/9ae813168a4f921968579bf889528dbc.mp3
还有解析的地址，能否直接下载，而不是显示地址，这样代码该如何写？

**Comment by vkkrcom** [comment]
> 请问您说的是解析哪一个视频地址呢

加了您的QQ，但一直没有通过，如何可以的话，有几个问题想请教一下，QQ810597，谢谢！

**Comment by iqiqiya** [comment]
<?php
$download_url = http://m10.music.126.net/20191021103956/aef2dd674865a997ed199e30f108b053/ymusic/8ae5/e063/1d74/9ae813168a4f921968579bf889528dbc.mp3;
header("Location: $download_url");
exit;
?>
这样子就可以了
我没收到qq好友请求鸭

**Comment by iqiqiya** [comment]
`<?php
$download_url = "http://m10.music.126.net/20191021103956/aef2dd674865a997ed199e30f108b053/ymusic/8ae5/e063/1d74/9ae813168a4f921968579bf889528dbc.mp3";
header("Location: $download_url");
exit;
?>`

**Comment by vkkrcom** [comment]
您的QQ是多少，我是在博客上看到的，或者麻烦您加一下我，QQ810597




------------------ 原始邮件 ------------------
发件人: "iqiqiya"<notifications@github.com>; 
发送时间: 2019年10月21日(星期一) 上午10:15
收件人: "iqiqiya/iqiqiya-API"<iqiqiya-API@noreply.github.com>; 
抄送: "孤竹无名"<1338932@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [iqiqiya/iqiqiya-API] 解析的视频地址，如何调用？能否解析地址后直接变成下载 (#5)




这样子就可以了
 我没收到qq好友请求鸭
